database:
  dbtype: mysql
  username: micro
  password: Ora#2021.passwd
  host: 129.158.203.151:3306
  dbname: stockappdb
  charset: utf8mb4
  parsetime: True
  maxidleconns: 10
  maxopenconns: 100

server:
  runmode: debug
  httpport: 8081
  readtimeout: 60
  writetimeout: 60

redis:
  addrs: 
  - "138.2.28.1:26379"
  password: Ora@2023.com
  db: 0
  poolSize: 1000
  minIdleConn: 100

kafka:
  addrs: 
  - "192.168.101.9:19092"
  - "192.168.101.9:29092"
  - "192.168.101.9:39092"

rabbitmq:
  user: guest
  password: Ora@2023.com
  addrs: 
  - "150.230.198.116:5672"
  port: 5672
  vhost: /

hivemq:
  addrs: 
  - "138.2.28.1:1883"
  password: Ora@2023.com
  username: admin
  topic: mylog
  QoS0: 0    // 至多一次
  QoS1: 1    // 至少一次
  QoS2: 2    // 确保只有一次